--TRIGGER--
--Basic Eligibility Criteria for Donor to donate plasma:
--1. Min 28 days since testing +ve for COVID, but less than 120 days
CREATE OR REPLACE TRIGGER COVID_REPORT
BEFORE INSERT
ON PLASMA_DETAILS
FOR EACH ROW
BEGIN
    IF (SYSDATE - (:NEW.DATE_OF_COVID_REPORT)) <=28 OR (SYSDATE - (:NEW.DATE_OF_COVID_REPORT)) > 128 THEN
        DBMS_OUTPUT.PUT_LINE('OOPS! Not Eligible');
        RAISE_APPLICATION_ERROR(-20000, 'RECORD IS ILLEGAL');
    END IF;
END;

--2. Age should be between 18-65 years & MIN weight should be 50 kgs
CREATE OR REPLACE TRIGGER ELIGIBLE_FOR_PLASMA_DONATION
BEFORE INSERT OR UPDATE 
ON DONOR
FOR EACH ROW
BEGIN
    IF :NEW.AGE>65 OR :NEW.AGE<=18 OR :NEW.WEIGHT<50 THEN
        DBMS_OUTPUT.PUT_LINE('OOPS! Not Eligible For Plasma Donation');
        RAISE_APPLICATION_ERROR(-20000, 'RECORD IS ILLEGAL');
    END IF;
END;

--CHECK if donor is suffering from serious illness
CREATE OR REPLACE TRIGGER SUFFER_FROM_ILLNESS
BEFORE INSERT
ON DONOR
FOR EACH ROW
BEGIN
    IF :NEW.SUFFERING_FROM_SERIOUS_ILLNESS = 'YES' OR :NEW.SUFFERING_FROM_SERIOUS_ILLNESS = 'Yes' OR :NEW.SUFFERING_FROM_SERIOUS_ILLNESS = 'yes' THEN
        DBMS_OUTPUT.PUT_LINE('OOPS! Not Eligible For Plasma Donation');
        RAISE_APPLICATION_ERROR(-20000, 'RECORD IS ILLEGAL');
    END IF;
END;
